version: '2'
services:
  sonarqube:
    container_name: 'sonarqube'
    image: sonarqube:6.2-alpine
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    depends_on:
      - postgres
    volumes:
      - sonarqube_location:/opt/sonarqube
  postgres:
    container_name: 'sonarqube_postgres'
    image: 'postgres:9.6.2-alpine'
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
  sonarqube_location:
